# docker compose -f dockerfiles/local_dev/docker-compose.yaml up
services:
  db:
    image: postgres:16
    # container_name: postgres
    environment:
      - POSTGRES_DB=backend_development
      - POSTGRES_USER=loco
      - POSTGRES_PASSWORD=loco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    # visit http://localhost:8081/?pgsql=db. 
    # Notice:  
    # select system as PostgreSQL
    # the server name should be "db" which matches the name defined above.
    # the database should be "backend_development".
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  postgres_data: